### PR TITLE
Updated screenshots from System Inventory

### PR DESCRIPTION
**Pull request by JuanGarriuz**
## Description

The `Inventory data` dashboard was changed in the latest version. We want to reflect the changes.

## Evidences

> user-manual/capabilities/system-inventory/generating-system-inventory-reports.html

image

> user-manual/capabilities/system-inventory/viewing-system-inventory-data.html

image

image

## Test

Navigate to the sections of the documentation mentioned in the evidence and verify that they correspond to the correct version of the application [4.10.1]

- [ ] user-manual/capabilities/system-inventory/generating-system-inventory-reports.html
- [ ] user-manual/capabilities/system-inventory/viewing-system-inventory-data.html

### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Review by guidomodarelli — CHANGES_REQUESTED** [review]
Fix frame on screenshots: https://docs.google.com/presentation/d/1S-u3XIFAJF1IKD7lzKcDOOc23JWyiLkt3E9UR5spA9Q/mobilepresent?slide=id.g14394bae8f4_1_18

**Review by chantal-kelm — CHANGES_REQUESTED** [review]
The way of marking the sections in the images should be corrected.

**Comment by guidomodarelli** [comment]
🟢 Test

image
image
image
image
image
image

**Review by chantal-kelm — APPROVED** [review]
CR: ✅ 
TEST: ✅ 

Captura de pantalla 2024-12-19 a la(s) 9 39 06 a  m
Captura de pantalla 2024-12-19 a la(s) 9 39 22 a  m
Captura de pantalla 2024-12-19 a la(s) 9 39 34 a  m
Captura de pantalla 2024-12-19 a la(s) 9 39 46 a  m

**Review by javimed — APPROVED** [review]

**Pull request merged**
