### PR TITLE
Update ossec_pci_dss.rst

### PR DESCRIPTION
**Pull request by SolarBoy3**
At first I noticed that 'use' should be 'used' at line 13. Then as I read the sentence a couple of times, it was clear it needed to be two sentences. Then I proof read a few more parts. Hope you like the updates. Plan to help more.

### CODE REVIEW

**Comment by snaow** [comment]
Hi @SolarBoy3,

Thanks for taking your time to improve the documentation, we really appreciate it.

Currently we are working on a new design and documentation, including all the features developed for Wazuh 1.2 release.

Again thanks, best regards,

Pedro S.

**Comment by SolarBoy3** [comment]
Hi Pedro,
  I will be building a Wazuh 2.0 system soon, and thus going through the
new documentation. I'd like to help contribute with documention suggested
corrections. I see a few right away, but I am not sure how to do that. I am
looking at the "dev" docs: https://documentation-dev.wazuh.com/index.html
Do I need a 'Read the Docs' account? I edited the 1.x docs with my GitHub
account and the 'Edit on GitHub' link in the upper right hand corner. For
the "dev" docs at the link above there is only 'View page source' in the
upper right hand corner. Please let me know if this is just too soon to
help out and you have documentation locked. Have a great weekend.

    - Steven B. Reeves

www.SolarBoy.org
Steve@SolarBoy.org
Think about it...
  CLEAN - Clean Local Energy Accessible Now
  PACE - Property Accessed Clean Energy

**Comment by jlruizmlg** [comment]
Hi @SolarBoy3 you don't need readthedoc, you can modify directly in this repository, only need to choose the branch 2.0 and send your pull request.

Every couple days we upload the new content, fix, pull request, etc to https://documentation-dev.wazuh.com/index.html

I hope it helps.

**Comment by SolarBoy3** [comment]
Thank you Jose,
  I will try that soon. Looking forward to contributing. Any chance anyone
will be going to LinuxFest NW?

    - Steven B. Reeves

www.SolarBoy.org
Steve@SolarBoy.org
Think about it...
  CLEAN - Clean Local Energy Accessible Now
  PACE - Property Accessed Clean Energy

**Comment by jlruizmlg** [comment]
I don't know about my coworkers, I'm in the east coast, difficult for me! But i would loved!

We will be at BSidesChicago, also we are sponsors there.

**Pull request merged**
