### PR TITLE
Wazuh Cloud - Add Canada Region

### PR DESCRIPTION
**Pull request by sultanovich**
## Description

This PR adds Canada Region on Wazuh Cloud.

### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [ ] Adds or updates meta descriptions accordingly.
- [ ] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [ ] Uses present tense, active voice, and semi-formal registry.
- [ ] Uses short, simple sentences.
- [ ] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Comment by sultanovich** [comment]
Hi @javimed , Could you check this PR? This change includes Canada in the regions available to apply for environments in Wazuh cloud.

Thanks,

**Comment by javimed** [comment]
@sultanovich I can see that for each region we're referring in the way you can see highlighted in the following images:

imagen
imagen
imagen

However, in this PR we're referring in the way highlighted below.

imagen

This doesn't look consistent. Are we ok with it? Why not using the full region names in the way AWS does?

**Comment by sultanovich** [comment]
Hi @javimed , is correct what you indicate. The problem is that we have been using part of the name of the AWS regions to identify them in the documentation, but in the case of the new region in Canada `central` I'm not sure if it will be clear to the customer.

image


It would be best to use the full name as [described by AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions).

image

I am consulting internally to confirm how we want to apply the change, as soon as I have an answer I will update it here.

**Comment by sultanovich** [comment]
Hi @javimed , we have defined to move forward with this modification as proposed. 
We are preparing a new change later to standardize the documentation so that all regions are identified in the same way. As soon as it is ready we will send it as a new PR for your review.

**Comment by javimed** [comment]
Hi @sultanovich . A second read of this comment now makes me think you want to merge this PR in the way it is now without addressing the consistency concerns I mentioned above. Please link the issue where it's planned to make these changes.

**Pull request merged**
