### PR TITLE
Update wazuh_server_deb.rst

### PR DESCRIPTION
**Pull request by SolarBoy3**
On line 61, I removed the sudo during install, as I have to be su to even begin this process. Might be better to be consistent and leave sudo off or comment on it.
curl -sL https://deb.nodesource.com/setup_6.x | bash -

### CODE REVIEW

**Comment by SolarBoy3** [comment]
At the end of step three in the section “Installing Wazuh API” (https://documentation.wazuh.com/current/installation-guide/installing-wazuhserver/wazuh_server_deb.html#wazuh-server-deb) we are prompted at tty to: 
= Don’t forget run the API configuration running the script /var/ossec/api/scripts/configure_api.sh =
 
When following this step-by-step install process, should we run this script now or wait till later at this point:
https://documentation.wazuh.com/current/installation-guide/optional-configurations/securing-api.html
If waiting, should the documentation reference that (to wait) and refer to the above page, letting everyone know that we will take this step at a later point? 

Also you might update the script to read:
= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh =

**Comment by alberpilot** [comment]
Hello @SolarBoy3 

  To run the script is optional. I mean, the Wazuh API will works without run this script. Indeed, the message "Don’t forget run the... " encourages us to think that is a mandatory step, but we did it in this way in order to simplify the installation process. So we will change these messages "Don't forget" in order to be clear at this point and avoid confussions about this optional step. 

  Thanks a lot for your feedback! Really apreciate. 
Best regards, 
Alberto R.

**Comment by SolarBoy3** [comment]
I thank you for any security help (more often missing from software developers setup docs). Personally, I take it as a mandatory step and always implement. I understand your desire to make the install smoother and quicker. For me personally, the process is not too long and I consider the documentation well beyond excellent. I may not be your target audience, as I have been working with computers for forty years now (VIC-20/Apple II) and Linux off/on for a decade (more on these days!). Just not a programmer. Have a great day everyone.

**Comment by alberpilot** [comment]
It's nice to see how professionals with that background uses Wazuh. :)

**Pull request merged**
