### PR TITLE
Update wazuh_agent_deb.rst

### PR DESCRIPTION
**Pull request by davidlwillson**
Need to specify the codename in the repo file, at least on Xenial, but I suppose on others, too. This will pull it in from the OS.

### CODE REVIEW

**Comment by jlruizmlg** [comment]
Hi, @davidlwillson is not necessary anymore, we have only one .deb for all distributions.

**Comment by davidlwillson** [comment]
Sure, but without the codename, apt won't use the repo. You'll get this, instead:

```
# apt-get update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/wazuh.list (Component)
E: The list of sources could not be read.
```

**Comment by jlruizmlg** [comment]
Hi @davidlwillson can you show me your /etc/apt/sources.list.d/wazuh.list? I just test it and works for me in a Xenial:

```
root@ip-172-31-38-108:/home/ubuntu# echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/3.x/apt/ stable main
root@ip-172-31-38-108:/home/ubuntu#  curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
OK
root@ip-172-31-38-108:/home/ubuntu# apt-get udpate
E: Invalid operation udpate
root@ip-172-31-38-108:/home/ubuntu# apt-get update
Hit:1 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:4 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/main Sources [868 kB]
Get:5 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/restricted Sources [4808 B]
Get:6 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/universe Sources [7728 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:8 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/multiverse Sources [179 kB]
Get:9 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7532 kB]
Get:10 https://packages.wazuh.com/3.x/apt stable InRelease [5241 B]
Get:11 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/universe Translation-en [4354 kB]
Get:12 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:13 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:14 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Sources [286 kB]
Get:15 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [3404 B]
Get:16 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [185 kB]
Get:17 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [7968 B]
Get:18 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [681 kB]
Get:19 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [285 kB]
Get:20 http://security.ubuntu.com/ubuntu xenial-security/main Sources [104 kB]
Get:21 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [565 kB]
Get:22 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [229 kB]
Get:23 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.2 kB]
Get:24 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8052 B]
Get:25 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/main Sources [3428 B]
Get:26 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Sources [4904 B]
Get:27 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4860 B]
Get:28 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [3220 B]
Get:29 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6616 B]
Get:30 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3768 B]
Get:31 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2600 B]
Get:32 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [48.9 kB]
Get:33 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [1520 B]
Get:34 https://packages.wazuh.com/3.x/apt stable/main amd64 Packages [1875 B]
Get:35 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [408 kB]
Get:36 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [179 kB]
Get:37 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [190 kB]
Get:38 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [98.9 kB]
Get:39 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3208 B]
Get:40 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1408 B]
Fetched 24.6 MB in 4s (5949 kB/s)
Reading package lists... Done
root@ip-172-31-38-108:/home/ubuntu# cat /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/3.x/apt/ stable main
root@ip-172-31-38-108:/home/ubuntu#
```

**Comment by davidlwillson** [comment]
That's because you used 'stable' for the codename, which apparently also works. But, the website has nothing in that position, which doesn't work.

**Comment by davidlwillson** [comment]
You have `.../apt stable main` the website has `..../apt main`.

**Comment by jlruizmlg** [comment]
You are right!!! Is wrong in the agent configuration,,, can you change your pull request for the next one? To keep consistency between installations, good catch!!

```echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/3.x/apt/ stable main

**Comment by davidlwillson** [comment]
Done.

**Comment by jlruizmlg** [comment]
@davidlwillson Thanks!!! as always!! and apologize for my error I was looking the manager installation, not the agent!

**Comment by davidlwillson** [comment]
Hey, just FYI... I just had a machine where 'stable' didn't work but the real codename ('xenial') did. Here's a log:

```
dlwillson@ip-172-31-24-8:~$ echo "deb https://packages.wazuh.com/apt stable main" | sudo tee /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/apt stable main
dlwillson@ip-172-31-24-8:~$ sudo apt update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:4 https://packages.wazuh.com/apt stable InRelease                           
Err:5 https://packages.wazuh.com/apt stable Release
  403  Forbidden
Hit:6 http://security.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done
E: The repository 'https://packages.wazuh.com/apt stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
dlwillson@ip-172-31-24-8:~$ echo "deb https://packages.wazuh.com/apt $( lsb_release -c | awk '{print $2}') main" | sudo tee /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/apt xenial main
dlwillson@ip-172-31-24-8:~$ sudo apt update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease              
Ign:5 https://packages.wazuh.com/apt xenial InRelease                          
Get:6 https://packages.wazuh.com/apt xenial Release [2,657 B]
Get:7 https://packages.wazuh.com/apt xenial Release.gpg [819 B]
Get:8 https://packages.wazuh.com/apt xenial/main amd64 Packages [3,193 B]
Fetched 6,669 B in 0s (19.2 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
dlwillson@ip-172-31-24-8:~$ 
```

**Comment by jlruizmlg** [comment]
Hi @davidlwillson i just realize that the URL is wrong, fixed in the commit f38b1252ce3dcefe340416abf6d84656a444717b

**Pull request merged**
