### PR TITLE
Split Security Lake integration docs into Source and Subscriber sections

### LINKED ISSUE #7584: Amazon Security Lake integration as source should be moved to the Integrations Guide section
| Wazuh version |
|-------|
| 4.9.0-beta1 |

# Description

There are two separate Amazon Security Lake integrations: one that pulls data into Wazuh and a separate one that pushes data from Wazuh into the service.
The latter is maintained by the Indexer team, along with the other integrations under `Integrations Guide` (Splunk, Opensearch, Elasticsearch) and should be moved into that section.

A link should be added to point the user into the subscriber integration, and back from it into the source one, for ease of navigation.

### PR DESCRIPTION
**Pull request by f-galland**
## Description
This PR moves the Source AWS Security Lake documentation pages to the `integrations-guide` section, as it is maintained by the Indexer team.

resolves #7584 

### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Comment by f-galland** [comment]
Changes build without warnings:
```shell
(_venv) fede@tyner:~/src/wazuh-documentation (7584-split-security-lake-integration-in-source-subscriber-sections)
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v7.0.1
loading translations [en-US]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
reading sources... 
Copying static files for wazuh-doc-images...[100%] img/loading.gif                                                                                                                   
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.
```

**Comment by f-galland** [comment]
The changes are reflected correctly in the rendered HTML:

**Review by gdiazlo — DISMISSED** [review]
lgtm

**Review by javimed — COMMENTED** [review]
There's no mention to ASL in `/integrations-guide/index`.

**Review by gdiazlo — DISMISSED** [review]
lgtm

**Pull request merged**
