### PR TITLE
Reverted to the prefix word

### PR DESCRIPTION
**Pull request by DamianNud**
## Description
Reverted the `pdocix` word to the `prefix` word in the AWS "Supported services" section, which was wrongly modified by replacing `ref` with `doc`.
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Review by javiersanchz — APPROVED** [review]
LGTM ! :rocket:

**Review by nico-stefani — DISMISSED** [review]
LGTM

**Review by javimed — APPROVED** [review]

**Comment by javimed** [comment]
@DamianNud Why not fixing this on branch `4.9` instead? 4.9 is the current documentation branch and accepts hotfixes

**Comment by DamianNud** [comment]
@javimed You are right. I just changed the base branch to `4.9`.

**Review by nico-stefani — APPROVED** [review]

**Review by javimed — APPROVED** [review]

**Pull request merged**
