### PR TITLE
Adapt SCA available policies table with latest changes

### PR DESCRIPTION
**Pull request by chemamartinez**
## Description

This PR adapts the SCA available policies table with modified and added policies at https://github.com/wazuh/wazuh-ruleset/pull/776.

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

### CODE REVIEW

**Review by jctello — CHANGES_REQUESTED** [review]
We should be consistent on capitalization and chose either "CIS Benchmark" or "CIS benchmark"

**Comment by chemamartinez** [comment]
> We should be consistent on capitalization and chose either "CIS Benchmark" or "CIS benchmark"

Solved (478dea9bd329029f90f74ab6ce2819dd402ba6d7).

I have chosen to uppercase `Benchmark` as CIS does.

This change should be applied to the policies from which these names are taken:

https://github.com/wazuh/wazuh-ruleset/blob/c6c7d5d0515c3779edbd827412b127533ca4175c/sca/windows/cis_win2012r2.yml#L18

**Review by jctello — APPROVED** [review]
LGTM! :-)

**Review by davidfmiranda — APPROVED** [review]
LGTM

**Pull request merged**
