### PR TITLE
Add Alpine Linux installation procedure

### PR DESCRIPTION
**Pull request by ed108206**
## Description

Closes Issue #6285 Add Instruction on how to upgrade Alpine Linux Agent
### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [ ] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Review by mjcr99 — COMMENTED** [review]
Hi @ed108206

It seems your change makes the documentation not buildable, so there is something wrong with it. You can test your changes by building the documentation locally. 

To do it you have to checkout the branch with your changes, in this case, `git checkout update/alpine-install-procedure`, and then build the documentation with `make html-quick`. Before it, ensure yourself the `requeriment.txt` is satisfied, you can do it with `pip install -r requirements.txt`

This will generate a `build` folder with all the `.html` generated files. You can navigate through them to make sure that changes look as they pretend to do.

**Comment by ncvicchi** [comment]
Thanks @mjcr99 ! Also, please include some evidence in the PR description regarding the installation procedure, successful doc building and resulting documents.

**Comment by ed108206** [comment]
Attached the image with the compilation result after change

modif-compile

**Comment by ed108206** [comment]
view of document after changes made (new "APK" tab with instructions to update Wazuh Agent on Alpine Linux)
Upgrading Wazuh agents on Linux systems - Wazuh agent

**Review by mjcr99 — COMMENTED** [review]
Hi @ed108206

Good job with the build fix! Please remember to test your solution before requesting them to be reviewed. 

I have been researching your changes, they make the built `.html` file look as is pretended, but the change is a static one. 

By static I mean, the Wazuh version shown on the webpage won't change if the Wazuh version changes, resulting in a non-maintainable modification, since it will be necessary to update it manually every time a new Wazuh version is released.

You can have a look at the other options such as `APT` or `YUM`, they use variables to change automatically the shown version, for example `WAZUH_AGENT_RPM_PKG_INSTALL` or `WAZUH_AGENT_DEB_PKG_INSTALL`. These variables are set in the [replacements.py](https://github.com/wazuh/wazuh-documentation/blob/master/source/_variables/replacements.py), so modifying this file is necessary too.

**Comment by ed108206** [comment]
Please check the review

**Comment by ncvicchi** [comment]
LGTM!

**Review by ncvicchi — APPROVED** [review]

**Pull request merged**
