### PR TITLE
Add `--api` parameter when changing the API users passwords 

### PR DESCRIPTION
**Pull request by Enaraque**
|Related issue|
|---|
|https://github.com/wazuh/wazuh-documentation/issues/7564|

## Description

In versions prior to 4.8, it was not necessary to use the --api option when changing the passwords of API users with the --change-all option. In this version, it was modified so that the --api option must also be used.

This change does not appear in the documentation, so the --api option has been added to the command.

## Changes

Captura de pantalla 2024-07-26 a las 12 52 41

### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Review by CarlosALgit — CHANGES_REQUESTED** [review]
Change is needed for the final step in the step-by-step installation for the Wazuh Dashboard. You can find it here: https://github.com/wazuh/wazuh-documentation/blob/fcce1b134386e8a4e95ff7bea6cc160b0f8c1434/source/installation-guide/wazuh-dashboard/step-by-step.rst?plain=1#L141

**Comment by Enaraque** [comment]
# Update report

@CarlosALgit I fixed it [here](https://github.com/wazuh/wazuh-documentation/pull/7581/commits/03b58aa4165fcd259728f669a95901c7a6b9ced9). Thanks for your help!
Captura de pantalla 2024-07-26 a las 14 16 43

**Review by CarlosALgit — DISMISSED** [review]

**Review by teddytpc1 — APPROVED** [review]

**Review by javimed — APPROVED** [review]
This seems to be an issue of 4.8 docs as well. We should use `4.8` as the base branch here.

I can see other occurrences of changing api user credentials (for example [Offline installation](https://github.com/wazuh/wazuh-documentation/blob/03b58aa4165fcd259728f669a95901c7a6b9ced9/source/deployment-options/offline-installation/step-by-step.rst?plain=1#L422) and [Dashboard installation](https://github.com/wazuh/wazuh-documentation/blob/03b58aa4165fcd259728f669a95901c7a6b9ced9/source/installation-guide/wazuh-dashboard/step-by-step.rst?plain=1#L183)

**Comment by Enaraque** [comment]
I close the PR and open another one with `4.8` as the base branch and only the changes mentioned above.

**Pull request closed without merging**
