### PR TITLE
Update Azure diagnostic step

### PR DESCRIPTION
**Pull request by GGP1**
## Description

Updates the Azure diagnostic section.

### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Review by EduLeon12 — APPROVED** [review]
LGTM!

**Review by Selutario — APPROVED** [review]
LGTM!

**Comment by GGP1** [comment]
> This PR is updating the `/cloud-security/azure/activity-services/services/storage` section. What about the `/cloud-security/azure/activity-services/services/log-analytics`? Is updating the Diagnostic settings displayed there out of scope? Is there an issue to link to?
> 
> imagen

@javimed This PR's [issue](https://github.com/wazuh/wazuh/issues/21548) is aimed at updating the Azure Storage service documentation. The log analytics is a separate service that hasn't been tested and that has different configurations and additional steps.

I will open a new issue for that, perhaps it's convenient to keep this one blocked until both are ready.

**Comment by rauldpm** [comment]
<details><summary>Documentation compiled without errors :green_circle: </summary>

```
╰─➤  make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v7.0.1
loading translations [en-US]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 689 source files that are out of date
updating environment: 1 added, 8 changed, 1 removed
reading sources... [100%] user-manual/reference/daemons/wazuh-modulesd                                                                                                                                            
Copying static files for wazuh-doc-images...[100%] img/loading.gif                                                                                                                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user-manual/wazuh-indexer/wazuh-indexer-tuning                                                                                                                                           
generating indices... done
writing additional pages... not_found moved-content search done
copying images... [100%] images/manual/wazuh-indexer/indexer-cluster-with-shard-replicas-diagram.png                                                                                                              
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.

```

</details>

<details><summary>Image check :yellow_circle: </summary>

- Wrong reference in the image sequence, the next image referrences to `frameworkteststorage` but the previous references `wazuh.com`

image




</details>

**Review by rauldpm — COMMENTED** [review]
<details><summary>Documentation compiled without errors :green_circle: </summary>

```
╰─➤  make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v7.0.1
loading translations [en-US]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 689 source files that are out of date
updating environment: 1 added, 8 changed, 1 removed
reading sources... [100%] user-manual/reference/daemons/wazuh-modulesd                                                                                                                                            
Copying static files for wazuh-doc-images...[100%] img/loading.gif                                                                                                                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user-manual/wazuh-indexer/wazuh-indexer-tuning                                                                                                                                           
generating indices... done
writing additional pages... not_found moved-content search done
copying images... [100%] images/manual/wazuh-indexer/indexer-cluster-with-shard-replicas-diagram.png                                                                                                              
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.

```

</details>

<details><summary>Image check :yellow_circle: </summary>

- Wrong reference in the image sequence, the next image referrences to `frameworkteststorage` but the previous references `wazuh.com`

image




</details>

@GGP1 could we get a screenshot with the original wazuh.com?

**Pull request merged**
