### PR TITLE
Create requirements.txt

### LINKED ISSUE #392: Add requirements.txt file
Hi team,

it would be great to add a `requirements.txt` listing all the Python modules needed to build the wazuh-docs. Using this files it will be much easier to install all of them by running: 

`pip install -r requirements.txt`.

Regards,
Braulio

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #392 

See build results in https://github.com/wazuh/wazuh-documentation/issues/392#issuecomment-437911627 for verification of correct dependency versions.

Also, Closes #476 by mutual exclusion.

*[Test scripts and report can be found here](https://gist.github.com/cmccandless/a1d3a440b44ebadcc21cf77e67439aaa)

### CODE REVIEW

**Comment by JuanjiJG** [comment]
Hello @cmccandless,

Please change the destination branch to `3.7` and make sure there are no conflicts. Thanks!

**Comment by cmccandless** [comment]
@JuanjiJG 
> Please change the destination branch to 3.7 and make sure there are no conflicts. Thanks!

Done!

**Comment by cmccandless** [comment]
@JuanjiJG should I add instructions to the README clarifying that only `make html` is used?

**Comment by JuanjiJG** [comment]
Hello @cmccandless,

Thank you, but it's not necessary. We're planning to create a `CONTRIBUTING.md` file with proper instructions for how to compile and make changes to the documentation. We're also going to update the `README.md` file.

See the progress here: https://github.com/wazuh/wazuh-documentation/issues/216

I'll proceed to merge this Pull Request. Thanks a lot for your contribution and your efforts, it's truly appreciated.

Regards,
Juanjo

**Pull request merged**
