### PR TITLE
Add more static filters to documentation

### PR DESCRIPTION
**Pull request by danimegar**
|Related issue|
|---|
|wazuh/wazuh#4050|

## Description
The documentation does not include some static filter options and it is necessary to add them. The options that I added to documentation are:
- [x] same_destination_ip
- [x] same_src_user
- [x] same_protocol
- [x] same_action
- [x] same_url
- [x] same_data
- [x] same_extra_data
- [x] same_status
- [x] same_system_name
- [x] same_srcgeoip
- [x] same_dstgeoip
- [x] different_id
- [x] different_source_ip
- [x] different_destination_ip
- [x] different_src_port
- [x] different_location
- [x] different_src_user
- [x] different_user
- [x] different_protocol
- [x] different_action
- [x] different_data
- [x] different_extra_data
- [x] different_status
- [x] different_system_name
- [x] different_dstgeoip

### CODE REVIEW

**Comment by epol** [comment]
I think it may be useful to specify that `<same_field>` and `<different_field>` won't work with the default fields (like srcip, dstuser,...) and that the specific ones have to be used.

**Comment by davidfmiranda** [comment]
Hello Daniel,

I have reviewed your changes and they look good to me, but shouldn't we change the base branch to 3.12?

Regards,

David

**Comment by danimegar** [comment]
> Hello Daniel,
> 
> I have reviewed your changes and they look good to me, but shouldn't we change the base branch to 3.12?
> 
> Regards,
> 
> David

Yes, you are right. 
Thanks, David.

**Comment by alberpilot** [comment]
This PR is closed due to future modifications

**Comment by danimegar** [comment]
A new PR opened: #2385

**Pull request closed without merging**
