### PR TITLE
Add documentation on new Office365 module parameter

### PR DESCRIPTION
**Pull request by S-Bryce**
## Description

The recent changes made to Wazuh's Office365 module so that it can support government instances of Microsoft 365 (see https://github.com/wazuh/wazuh/pull/15010 for more detail) have resulted in the addition of a new parameter, `api_auth\api_type`. The documentation changes in this PR delineate the options & purpose of this new parameter, and update existing examples of how to configure the Office365 module with practical examples of the new parameter being specified within a configuration file.

Where possible these changes mirror the existing documentation for the Office365 module, but if any changes are necessary I am happy to make them.
## Checks
- [X] Compiles without warnings.
- [X] Uses present tense, active voice, and semi-formal registry.
- [X] Uses short, simple sentences.
- [X] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.
- [X] Uses three spaces indentation.
- [X] Adds or updates meta descriptions accordingly.
- [X] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

### CODE REVIEW

**Review by TomasTurina — COMMENTED** [review]
You need to fix this PR, you are including changes from 4.6 branch.

**Comment by S-Bryce** [comment]
> You need to fix this PR, you are including changes from 4.6 branch.

Fixed!

**Comment by TomasTurina** [comment]
Can you re-do this PR as you did with the PR in QA repository?

**Comment by TomasTurina** [comment]
@S-Bryce include only these three commits

image

**Review by TomasTurina — APPROVED** [review]

**Review by javimed — APPROVED** [review]
LGTM

**Pull request merged**
