### PR TITLE
Updated documentation for protocol in remoted

### PR DESCRIPTION
**Pull request by JcabreraC**
Hi Team,
this PR closes the issue #3356

## Description

The `protocol` section of `remoted` has been modified.
- User manual - Reference - Local configuration (ossec.conf) - remote

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

### CODE REVIEW

**Review by nmkoremblum — APPROVED** [review]
Nice! Very well written!

**Review by juliancnn — APPROVED** [review]

**Review by jnasselle — APPROVED** [review]
LGTM! But, in case you are open to suggestions, i would prefer to separate the whole statement into two ones (bullets maybe?) in order to improve visibility.

**Review by davidfmiranda — APPROVED** [review]
LGTM

**Review by nmkoremblum — APPROVED** [review]

**Review by nmkoremblum — CHANGES_REQUESTED** [review]
waiting for ipv6-related changes

**Review by juliancnn — APPROVED** [review]

**Review by jnasselle — APPROVED** [review]
LGTM!

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Pull request merged**
