### PR TITLE
Deprecating rootcheck from agent_control tool documentation

### PR DESCRIPTION
**Pull request by DProvinciani**
## Description

This pull request includes all the necessary changes in the Wazuh documentation after deprecating the rootcheck data output from the `agent_control` tool.

## Checks
- [x] It compiles without warnings.

### CODE REVIEW

**Review by palaciosjeremias — APPROVED** [review]
LGTM

**Review by davidfmiranda — APPROVED** [review]
LGTM

**Review by pereyra-m — APPROVED** [review]
LGTM!

**Comment by DProvinciani** [comment]
As we are keeping the possibility of trigger the rootcheck scan from this tool, closing the pull request as invalid.

**Pull request closed without merging**
