### PR TITLE
Changed the output of the ossec-logtest to the new wazuh-logtest

### LINKED ISSUE #3208: Change documentation to use new names of tools
According to the changes in the Wazuh CLIs, the documentation has to be updated.

- [Tools reference](https://documentation.wazuh.com/4.0/user-manual/reference/tools/index.html)
- Appearances of tools like `ossec-control` across the whole documentation

### PR DESCRIPTION
**Pull request by danimegar**
## Description

This PR fixes the output of the wazuh-logtest examples found in the documentation since ossec-logtest is deprecated. It closes #3208

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns.

### CODE REVIEW

**Review by jnasselle — CHANGES_REQUESTED** [review]
Hi @danimegar !

Nice job here! I saw only a few things to fix:
- Update rules: there are several rules that was changed (MITRE info and new groups i.e TSC)
   -  Rules id changed: 5710, 5712
- wazuh-logtest currently show `Type one log per line` and version message while is being executed. I recommend adding to this documentation only the first one to avoid updating this documentation every time version increases.

Thanks!

**Comment by danimegar** [comment]
Hello @jnasselle 

I added the `Type one log per line` to the wazuh-logtest output. I did not update the rules like 5710 or 5712 because I think they already are with MITRE or TSC data. Examples:
```
**Phase 3: Completed filtering (rules).
            id: '5710'
            level: '5'
            description: 'sshd: Attempt to login using a non-existent user'
            groups: '['syslog', 'sshd', 'invalid_login', 'authentication_failed']'
            firedtimes: '1'
            gdpr: '['IV_35.7.d', 'IV_32.2']'
            gpg13: '['7.1']'
            hipaa: '['164.312.b']'
            mail: 'False'
            mitre.id: '['T1110']'
            mitre.tactic: '['Credential Access']'
            mitre.technique: '['Brute Force']'
            nist_800_53: '['AU.14', 'AC.7', 'AU.6']'
            pci_dss: '['10.2.4', '10.2.5', '10.6.1']'
            tsc: '['CC6.1', 'CC6.8', 'CC7.2', 'CC7.3']'
    **Alert to be generated.
```
```
**Phase 3: Completed filtering (rules).
            id: '5712'
            level: '10'
            description: 'sshd: brute force trying to get access to the system.'
            groups: '['syslog', 'sshd', 'authentication_failures']'
            firedtimes: '1'
            frequency: '8'
            gdpr: '['IV_35.7.d', 'IV_32.2']'
            hipaa: '['164.312.b']'
            mail: 'False'
            mitre.id: '['T1110']'
            mitre.tactic: '['Credential Access']'
            mitre.technique: '['Brute Force']'
            nist_800_53: '['SI.4', 'AU.14', 'AC.7']'
            pci_dss: '['11.4', '10.2.4', '10.2.5']'
            tsc: '['CC6.1', 'CC6.8', 'CC7.2', 'CC7.3']'
    **Alert to be generated.
```
Thank you,
Daniel

**Review by jnasselle — APPROVED** [review]
LGTM!
Thank you very much @danimegar :+1:

**Review by davidfmiranda — APPROVED** [review]
LGTM

**Pull request merged**
