### PR TITLE
[New design] Iteration on new-design and general changes 17J

### PR DESCRIPTION
**Pull request by 0ryson**
- All titles (H2, H3, etc) are color: #404040;
- The dark blue color only is used for links.
- Bullet points on lists are color: #404040
- Added small padding-right for lists (10px) - only in desktop view
- Titles with the line underneath have more space above and below and have color: #404040;

Screenshot (5)

- Button: `Join our mailing list` is now `Open source community` and it leads to the Community page (website)
- Button: `Join our Slack channel` is now `Professional services` and it leads to the Services page (website)

   Screenshot (3)

- Fixed wrong numbers on lists, `pre` text inside `note` and other bugs in all docu

   Screenshot (6)

- Now the `note` background is: Strong color: rgba(0, 169, 229, 0.5) | Soft color: rgba(0, 169, 229, 0.1)
- Now the `warning` background is`: Strong color: rgba(255, 183, 0, 0.5) | Soft color: rgba(255, 183, 0, 0.1); and the text is dark

   screenshot__3_

- Menu no longer disappears when we search
- It has returned to the original design of the tables

   Screenshot (1)

### CODE REVIEW

**Comment by 0ryson** [comment]
### Changes in pre and code tags

Fixed the bug that not show the background in pre and code tags. Also, now they have less padding.

**Comment by saramoran** [comment]
After reviewing the whole thing, these are the changes that we need to make: https://github.com/wazuh/wazuh-website/issues/656#issuecomment-504961993

**Comment by 0ryson** [comment]
General corrections
Issue [#656 (comment)](https://github.com/wazuh/wazuh-website/issues/656#issuecomment-505363161)

**Comment by 0ryson** [comment]
General corrections 2
Issue [#656 (comment)](https://github.com/wazuh/wazuh-website/issues/656#issuecomment-506329744)

**Comment by 0ryson** [comment]
General corrections 3
Issue [#656 (comment)](https://github.com/wazuh/wazuh-website/issues/656#issuecomment-506631810)

**Comment by 0ryson** [comment]
General corrections 4
Issue [#656 (comment)](https://github.com/wazuh/wazuh-website/issues/656#issuecomment-506713886)

**Pull request merged**
