### PR TITLE
Update Azure Log Analytics images

### PR DESCRIPTION
**Pull request by fdalmaup**
## Description

Closes https://github.com/wazuh/wazuh/issues/21630. Updates some of the images of the Azure Log Analytics section after verifying the step-by-step guide.

### Docs building
- [x] Compiles without warnings.
### Code formatting and web optimization
- [x] Uses three spaces indentation.
- [x] Adds or updates meta descriptions accordingly.
- [x] Updates the `redirects.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).
### Writing style
- [x] Uses present tense, active voice, and semi-formal registry.
- [x] Uses short, simple sentences.
- [x] Uses **bold** for user interface elements, _italics_ for key terms or emphasis, and `code` font for Bash commands, file names, REST paths, and code.

### CODE REVIEW

**Review by GGP1 — CHANGES_REQUESTED** [review]
The [log-analytics-diagnostic-2.png](https://github.com/wazuh/wazuh-documentation/blob/80f7b36cd2ceeeb23df1b3c91e08dcd5045b69aa/source/images/cloud-security/azure/log-analytics-diagnostic-2.png) image from the [Sending logs to the Workspace](https://documentation.wazuh.com/current/cloud-security/azure/activity-services/services/log-analytics.html#sending-logs-to-the-workspace) section needs to be updated. This is what I see when I follow the steps from the documentation:

diagnostic_setting

**Comment by fdalmaup** [comment]
You are correct, that it is the initial screen, but following the mentioned step above the image: `Choose the log categories you want to collect from, under Logs Categories. Check the Send to Log Analytics workspace option under Destination details. Select the Log Analytics Workspace you created in previous steps.`, specifically, `Check the Send to Log Analytics workspace option`, the `Subscription` and `Log Analytics workspace` options appear.

**Review by GGP1 — APPROVED** [review]
LGTM

**Review by Selutario — APPROVED** [review]
LGTM

**Review by rauldpm — APPROVED** [review]

**Pull request merged**
