### PR TITLE
Include Wazuh 4.0 enrollment method in Docu

### PR DESCRIPTION
**Pull request by Arcapas**
Hi team,

## Description
This PR aims to include Wazuh 4.0 enrollment method blog post in the Documentation.

**Activities of the Issue:**
- [x] Take the content from the blog post draft: [Wazuh 4.0 enrollment method V1.0](https://docs.google.com/document/d/1Ov7HdZzyyuTGuYJD31fDR88bjgzWSvbb9Y4BlEO_IRI/edit?usp=sharing)
- [x] Talk with the author of the blog post, Jeremías Palacios
- [x] Review with Jeremías the information of the blog post to create the documentation section: [Wazuh 4.0 enrollment method V1.1](https://docs.google.com/document/d/1BhcVZplpapdUkZfkY7KQH2V7hatI4_BGKbYJZtA9DMo/edit?usp=sharing)
- [x] Edit the Doc with the information shared by Jeremías: [Wazuh 4.0 enrollment method V1.2](https://docs.google.com/document/d/1k7hUhG01lAR112gcP7d6Nk3hlVssE3RHr5I48wcMNWo/edit?usp=sharing)
- [x] Add images and make the final edition and format adjustment.
- [x] Editorial review by MarVergara 
- [x] Review the text with the content team.
- [x] I make new adjustments asked by Sandra 
- [x] Jeremias sent me some new material to add to this section
- [x] I make all the changes asked by Sandra

## Checks
- [x] It compiles without warnings.
- [x] Spelling and grammar. 
- [x] Used impersonal speech. 
- [x] Used uppercase only on nouns. 
- [x] Updated the `redirect.js` script if necessary (check [this guide](https://github.com/wazuh/wazuh-documentation/blob/master/NEW_RELEASE.md)).

Regards,
Damián

### CODE REVIEW

**Review by MarVergara — APPROVED** [review]
LGTM 👍

**Review by Arcapas — COMMENTED** [review]
LGTM. I made all the changes asked by @s-ocando in the `agent-enrollment.rst`

**Review by Arcapas — COMMENTED** [review]
@s-ocando please review

**Comment by Arcapas** [comment]
LGTM

**Review by s-ocando — APPROVED** [review]
LGTM

**Pull request merged**
