### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by vikman90** [comment]
Thank you @jsoref for your contribution !! 

I see that this is coherent with another changes in the Wazuh project and the ruleset.

Best regards.

**Comment by jsoref** [comment]
Yes, it's done using: https://github.com/jsoref/spelling
I just deployed wazuh yesterday, so I'm also sending PRs based on usage. I tend to send spelling PRs before using a tool to check project health and also as a proactive thanks before I start asking for help/features.

**Comment by vikman90** [comment]
You're very kind.

Your project is awesome! I wonder if it removed automatically the space in the table when fixing `begining` for `beginning`.

Thank you very much for your contribution again.
Best regards.

**Comment by jsoref** [comment]
No, that's totally manual. I haven't spent the time figuring out how to teach a program to do that. What I do is draft a pull request in GitHub and review the visual diff, which highlights such things, then I fix them and push again.

**Pull request merged**
